title:             Olympia Bears Baseball
email:             your-email@example.com
description:       Earn It.
baseurl:           "/olympia-baseball-website"
url:               "http://scottcame.github.io"

# Social Profiles
twitter_username:  OHSDBackers
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
